#!/bin/bash

clear

function httpfs {
    bin=/tmp/httpfs
    go build -o $bin ./httpfs/*.go
    echo -e "\n\e[1;34mhttpfs $@\e[0m\n"
    $bin "$@" &
    rm $bin
}

function httpc {
    echo -e "\n\e[1;35mhttpc $@\e[0m\n"
    go run ./httpc/*.go "$@"
}

function cleanup {
    kill $(jobs -p) &>/dev/null
}

trap cleanup EXIT

httpfs

sleep 0.3

httpc get http://localhost:8080
